### ISSUE TITLE
Can't seem to be able to add new esd

### ISSUE THREAD

**Issue by Spyne250** [thefifthmatt/ESDLang#3]
Hi, 

I'm having trouble getting an additional esd file into the talkesd bnds.
The help section specifies using the "extra" argument, but I was not able to get it to work.

I was using it in this way -extra t800006001=m60_00_00_00, I'm wondering if that is correct?

As an aside, I was also attempting to debug it myself in case I was using it incorrectly so as to not waste your time, and maybe attempt a fix if it needed fixing. But I could not build the project, it was telling me  the target frameworks were different. I tried changing them but I'm way out of my depth with that. Is there a way I can get it working?

Regardless, thank you such amazing resources

**Comment by KirmesBude** [comment]
I am facing the same issue. Did you find a solution for it in the meantime?

**Comment by Spyne250** [comment]
No unfortunately

**Comment by KirmesBude** [comment]
For my usecase I was able to just reuse existing esd files. But I am now using https://github.com/GompDS/ESDStudio and I see and option to add a new bsn there. Maybe you can try out that.

**Comment by gracenotes** [comment]
Sorry, this was previously broken. I have verified it is fixed in v0.4.1. ESDStudio uses its own game-packing so it also works for that.
