### ISSUE TITLE
DS2: Expects gameparam_dlc2.parambnd.dcx, and can't handle enc_regulation.bnd.dcx

### ISSUE THREAD

**Issue by kingborehaha** [thefifthmatt/ESDLang#4]
gameparam_dlc2.parambnd.dcx isn't generated as part of more modern DS2 modding workflow, and in those cases ESDLang will quit.

> System.Exception: Failed to load C:\Program Files (x86)\Steam\steamapps\common\Dark Souls II Scholar of the First Sin\Game\gameparam_dlc2.parambnd.dcx: System.Exception: Failed to load C:\Program Files (x86)\Steam\steamapps\common\Dark Souls II Scholar of the First Sin\Game\gameparam_dlc2.parambnd.dcx: System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\Steam\steamapps\common\Dark Souls II Scholar of the First Sin\Game\gameparam_dlc2.parambnd.dcx'.

If ESDLang could handle enc_regulation.bnd.dcx then there wouldn't be a problem.

**Comment by Regiar3dev** [comment]
I'm having the same issue here. Don't know if I'm doing something wrong...

**Comment by gracenotes** [comment]
SoulsFormats is advanced enough by now that it reads enc_regulation.bnd.dcx as a plain BND without any issues. If that was the case in v0.3 I suppose this could have also been resolved by setting the `-params` argument manually. But now the default param name is the correct one and it does read it.
